### ISSUE TITLE
Mangio-Crepe implementation

### ISSUE THREAD

**Issue by ingrid-z** [IAHispano/Applio-Installer#1]
Is there something going wrong with mangio-crepe
1. Hop length is 64 by default, but when you train with mangio-crepe the console shows 128 hop length.
2. mangio-crepe is not working for me. When I use this algorithm my computer crank up at full speed applio uses all my resources until BSOD. I never get it done in extracting feature stage.
3. No error messages. sign

SPEC:
5950X
48GB RAM
RTX 4080

**Comment by aitronssesin** [comment]
Use rmvpe is the best for the moment and this is the repo for the installer report issues  to the main repo https://github.com/IAHispano/Applio-RVC-Fork
