### ISSUE TITLE
huggingface download

### ISSUE THREAD

**Issue by Dibucci** [IAHispano/Applio-Installer#10]
![image](https://github.com/IAHispano/Applio-Installer/assets/25534395/5b3bd970-f1c9-46cf-bdf4-bda96283b64b)
![image](https://github.com/IAHispano/Applio-Installer/assets/25534395/90fc6976-8ca7-4b01-83a5-ffd44d437969)
so, as the images show, it installed but it can't download that file from huggingface and it just crashes... idk where to go from here?

DUE NOTE! This is my 2nd time installing 4.0.0, I deleted the folder when it did this the first time, thinking maybe it was just a misshap so I re-installed it, bt it still happened

**Comment by Dibucci** [comment]
I don't have really any knowladge in python/ coding, So when I see a bunch of ".bat" I don't touch it unless it tells me to either in an installer or on the github so idk if I should just click this 
![image](https://github.com/IAHispano/Applio-Installer/assets/25534395/f31caf83-a814-40ea-96ce-30cd7caaf0c7)
in the Applio-RVC-Fork or
![image](https://github.com/IAHispano/Applio-Installer/assets/25534395/1c627127-0c00-4c1c-bf7e-78d29a33f878)
click the same bat in the folder before it... Or if I use them at all cuz I don't want to mess anything up

**Comment by Dibucci** [comment]
Oh.... nvm... I just clicked the go-applio.bat and its downloading things.... it didn't do that before for some odd reason tho....hmmm... anyhow sorry for the possable waist of time

**Comment by bygimenez** [comment]
> Oh.... nvm... I just clicked the go-applio.bat and its downloading things.... it didn't do that before for some odd reason tho....hmmm... anyhow sorry for the possable waist of time

Did you get any errors?

**Comment by Dibucci** [comment]
no, no errors popped up. I was able to press ctrl + L-click on the huggingface URL in the first CMD, the one I showed the pic of, and it downloaded that file manuly and I put it in the proper folder. so idk why it couldn't download that first part. Then as i said after i ran the go-applio.bat, it downloaded what it needed and just ran this time... idk what to make of it tbh but its working now

**Comment by Dibucci** [comment]
I will say the audio it makes is a lot better now than the old RVC I have on my system xD
