### ISSUE TITLE
Unable to start installation, am I missing something?

### ISSUE THREAD

**Issue by xiujk71** [IAHispano/Applio-Installer#12]
Hello, I am trying to install Applio on my PC but the installation won't start.
As you can see from the screenshot below, I do have git installed.
Clicking the Install button only make the "This procedure may require a significant amount of time and could potentially result in a temporary reduction in your computer's performance..." appear, and does nothing else on my end.

![cmd_ghDFqNXzfW](https://github.com/IAHispano/Applio-Installer/assets/15521366/eec8e0cd-0945-474c-ab04-59701a0aa649)

Tested on both 4.0.1 and 4.0.0 installers. Am I missing something other than having a git installation?

**Comment by bygimenez** [comment]
Thanks for the warning, it seems to be a problem with Applio Installer. While we fix it I recommend you to install Applio with this .bat https://github.com/IAHispano/Applio-RVC-Fork/releases/download/v2.0.0/install_Applio-windows.bat
