### ISSUE TITLE
ModuleNotFoundError: No module named 'fairseq' AMD

### ISSUE THREAD

**Issue by CrouchHolmes** [IAHispano/Applio-Installer#13]
I have a module error. The picture is attached
![cmd_5RcFHP8GkL](https://github.com/IAHispano/Applio-Installer/assets/108918294/2b3d855c-0b3d-4e76-a3bb-b5fe53a904b8)
![cmd_sB1Gf5jAUb](https://github.com/IAHispano/Applio-Installer/assets/108918294/673b468c-9907-4e6b-8252-25ee52e5b5a3)

**Comment by bygimenez** [comment]
> I have a module error. The picture is attached ![cmd_5RcFHP8GkL](https://user-images.githubusercontent.com/108918294/276929053-2b3d855c-0b3d-4e76-a3bb-b5fe53a904b8.png) ![cmd_sB1Gf5jAUb](https://user-images.githubusercontent.com/108918294/276929142-673b468c-9907-4e6b-8252-25ee52e5b5a3.png)

https://docs.applio.org/faq/no-module/

**Comment by CrouchHolmes** [comment]
> > I have a module error. The picture is attached ![cmd_5RcFHP8GkL](https://user-images.githubusercontent.com/108918294/276929053-2b3d855c-0b3d-4e76-a3bb-b5fe53a904b8.png) ![cmd_sB1Gf5jAUb](https://user-images.githubusercontent.com/108918294/276929142-673b468c-9907-4e6b-8252-25ee52e5b5a3.png)
> 
> https://docs.applio.org/faq/no-module/
![cmd_pmRU7z8wd7](https://github.com/IAHispano/Applio-Installer/assets/108918294/bf28371d-fcc5-4292-8cd0-5467e2e5e780)
not works
