### ISSUE TITLE
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory GPU AMD

### ISSUE THREAD

**Issue by CrouchHolmes** [IAHispano/Applio-Installer#16]
![image](https://github.com/IAHispano/Applio-Installer/assets/108918294/c2f9465d-2d31-440f-94af-012445c82959)

**Comment by bygimenez** [comment]
> ![image](https://user-images.githubusercontent.com/108918294/277109112-c2f9465d-2d31-440f-94af-012445c82959.png)

This error has to do with Applio-RVC-Fork not with the installer, please refer to the (respective repository)[https://github.com/IAHispano/Applio-RVC-Fork/issues].
