### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by playerbrodie** [IAHispano/Applio-Installer#17]
I've installed a couple times now, and both times I get this when I run the bat.

```
Starting Applio with runtime for Nvidia support (you must have it installed)...
The system cannot find the path specified.
Press any key to continue . . .
```

![image](https://github.com/IAHispano/Applio-Installer/assets/81574239/ff1a8628-604c-4aec-9ce5-4a3ee5458a0c)

**Comment by bygimenez** [comment]
If I understand correctly, you are not using Applio Installer.
