### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorboard'

### ISSUE THREAD

**Issue by enzomtpYT** [IAHispano/Applio-Installer#18]
Hello ! After the installation when this screen appears
![image](https://github.com/IAHispano/Applio-Installer/assets/40535918/fbee0049-4ffd-46d1-945f-9c7aeeba773b)
A terminal window appears with these lines :
`Traceback (most recent call last):                                                                                        File "C:\Program Files\Applio\Applio-RVC\Applio-RVC-Fork\infer-web.py", line 3, in <module>                               from tensorboard import program                                                                                     ModuleNotFoundError: No module named 'tensorboard'`

**Comment by bygimenez** [comment]
> Hello ! After the installation when this screen appears ![image](https://user-images.githubusercontent.com/40535918/280482063-fbee0049-4ffd-46d1-945f-9c7aeeba773b.png) A terminal window appears with these lines : `Traceback (most recent call last): File "C:\Program Files\Applio\Applio-RVC\Applio-RVC-Fork\infer-web.py", line 3, in <module> from tensorboard import program ModuleNotFoundError: No module named 'tensorboard'`

https://docs.applio.org/faq/no-module/
