### ISSUE TITLE
"You are executing the script with administrator privileges. Please run it without elevated permissions."

### ISSUE THREAD

**Issue by DougieGalaxy** [IAHispano/Applio-Installer#21]
I've been getting the same error message forever, whenever I try to install it (from the .exe or the .bat) it gives me the same message saying "You are executing the script with administrator privileges. Please run it without elevated permissions. Please, hit enter to exit."

I'm not executing it as admin, literally just double clicked without giving any extra permissions.

**Comment by bygimenez** [comment]
Right click --> Properties. Uncheck the box "run this program as administrator", maybe you have this option enabled and that's why when you double click it opens as administrator.
