### ISSUE TITLE
5.3.5 Installer totally broken

### ISSUE THREAD

**Issue by ingrid-z** [IAHispano/Applio-Installer#22]
Turn off both of Windows Defence and firewall.

If install in default path C:\users\xxxx\Desktop , it will install correctly.
If I choose the path like D:\  , the installer just goes crazy which will install Applio-RVC-Fork to windows temporary folder.

And this installer also broken Applio function in many ways.
Like I set hop_length to 10, what I get is filename_e10_s10 and e20_s20 and so on what It's suppose to be e10_s920.
Also data process and feature extract all has (too much)error shows up.

Did you guys...even test the installer before release?!

**Comment by aitronssesin** [comment]
You can not install applio in an external drive

**Comment by aitronssesin** [comment]
![image](https://github.com/IAHispano/Applio-Installer/assets/74368135/d63de8c8-af17-4855-926c-824043ded394)

**Comment by aitronssesin** [comment]
Also this installer uses the official installer and thoses features are working correctly.

**Comment by ingrid-z** [comment]
> You can not install applio in an external drive

Why make you think D:\ is a external drive? lol
I've read installation before I install applio.

**Comment by aitronssesin** [comment]
Because it's not the default drive in your system

**Comment by ingrid-z** [comment]
> Because it's not the default drive in your system

D drive is a internal SATA SSD in my system.

I've use applio since it was 0.x/1 version.
I just do the same thing to update the applio.
I even do the fresh installation, it still not working for me.

**Comment by aitronssesin** [comment]
Yes but it isn't your system default.

**Comment by aitronssesin** [comment]
Applio underwent changes, and prior to the training update, it was malfunctioning and not optimized. We are currently working on adding support for other drives, but we're struggling to identify the error causing the issue.

**Comment by aitronssesin** [comment]
Also you can try using the installer with admin perms but I don't know if it's gonna work.

**Comment by ingrid-z** [comment]
> Yes but it isn't your system default.

I've tried everything I can,
YES, I haven't altered anything even the installation path, it just not working.

Does installer install runtime? or it uses conda env now?

**Comment by aitronssesin** [comment]
Conda env

**Comment by aitronssesin** [comment]
Read my other comments

**Comment by ingrid-z** [comment]
> Also you can try using the installer with admin perms but I don't know if it's gonna work.

Yes, but not working.

**Comment by aitronssesin** [comment]
Using the default installation path? Did you tried?

**Comment by aitronssesin** [comment]
Because I have tried the installer in different machines and it was working

**Comment by ingrid-z** [comment]
> Using the default installation path? Did you tried?

read my other comment, yes.
It's was working in 5.0.0 installer, but I donlt know why it not working now.
Maybe I should try the installer.bat from the other project.

**Comment by aitronssesin** [comment]
Yes try the bat but I have to say you that the exe installer uses the same bat from the other repo

**Comment by ingrid-z** [comment]
I think I found a bug.
If you do the feature extract with rmvpe(cpu) will work.
But if you do the feature extract with rmvpe_gpu then train which will not work properly. you will get filename_e10_s10 something like this.
