### ISSUE TITLE
Batch process error

### ISSUE THREAD

**Issue by adamwiverson** [IAHispano/Applio-Installer#4]
Processing a single file is fine, but when it comes to batch, it gives me this error.

Traceback (most recent call last):
  File "F:\Applio-RVC-Fork\lib\infer\modules\vc\modules.py", line 657, in vc_multi
    info, opt = self.vc_single_dont_save(
TypeError: vc_single_dont_save() missing 1 required positional argument: 'f0_autotune'

I didn't have this issue on Applio 3, but this happens when it comes to Applio 4. I'm using the Nvidia RTX 3090 in this case.

![Screenshot 2023-09-28 235422](https://github.com/IAHispano/Applio-Installer/assets/118083933/2e368563-e75f-4482-b159-86b1b3dd06ae)

**Comment by TheUserNil** [comment]
Fixed https://github.com/IAHispano/Applio-RVC-Fork/commit/85d2c2f94efd7709979caf461a7f04db4ea48b1c

**Comment by TheUserNil** [comment]
In addition, errors are reported at https://github.com/IAHispano/Applio-RVC-Fork.

**Comment by adamwiverson** [comment]
I think it's better, the batch is now working. Thank you!
