### ISSUE TITLE
Installer restarted my machine without user permission [dataloss]

### ISSUE THREAD

**Issue by eyaler** [IAHispano/Applio-Installer#5]
4.0.0 on windows 11

**Comment by bygimenez** [comment]
The installer doesn't have the necessary permissions to perform that action. Had you previously installed the Build Tools and VCRedist, or did you let the installer do it?

**Comment by eyaler** [comment]
indeed i suspect it was the VC installer. if installer calls VC and VC reboots then installer can reboot... from user point of view you might have as well called `shutdown /r`. it seems that this is a known issue of VC and I suggest adding explicit warning text for the VC checkbox stating that the machine might auto reboot without warning.
