### ISSUE TITLE
Installer does not recover from failed installation due to existing folder

### ISSUE THREAD

**Issue by eyaler** [IAHispano/Applio-Installer#6]
4.0.0 on windows 11
fatal: destination path 'C:\Users\eyalg\Desktop\Applio-RVC-Fork' already exists and is not an empty directory.
Cloning process completed with exit code 128

**Comment by bygimenez** [comment]
This is a GIT thing, you must select an **EMPTY folder** to install Applio.

**Comment by eyaler** [comment]
of course. in this case you could skip the git clone.

**Comment by bygimenez** [comment]
> of course. in this case you could skip the git clone.

The installer will do a git clone on a path containing an EMPTY folder and you will be able to continue installing Applio, otherwise GIT will not allow to continue. This is not an error or a bug.

**Comment by eyaler** [comment]
just to make sure my user story was clear: the installer did the git clone. later i had to abort the installation (due to the reboot issue). when i tried to re-install i hit this error.

**Comment by bygimenez** [comment]
To address the reboot issue, I would require more detailed information. Regarding the problem "already exists and is not an empty directory," the solution is to create an empty folder and then copy the path to that folder and paste it into the installer. Again, this is a GIT issue, not a bug or problem related to the installer.
