### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bearwal** [IAHispano/Applio-Installer#8]
after I click install, it just says 

Cloning into 'F:\Applio'...
Cloning process completed with exit code 0
Finished cloning repository

and nothing else happens, doesnt show ny other text, I already  tried with previous versions and turned off antivirus but nothing seems to work

**Comment by bygimenez** [comment]
> after I click install, it just says
> 
> Cloning into 'F:\Applio'... Cloning process completed with exit code 0 Finished cloning repository
> 
> and nothing else happens, doesnt show ny other text, I already tried with previous versions and turned off antivirus but nothing seems to work

Hey [bearwa](https://github.com/bearwal) How are you? I'm sorry you're having this problem, we're going to try to fix it. I need to know a few things like; are you connected to the internet? did you use AMD or NVIDIA?

**Comment by bearwal** [comment]
yes, im online, im using nvidia 2060 super

**Comment by bygimenez** [comment]
Okay, how long have you been waiting for it to install?

**Comment by bearwal** [comment]
probably like 1 hour already, i tried with the v2 of the installer but it doesnt add any files to the folder

**Comment by bygimenez** [comment]
I've updated something, open the .exe and try again.

**Comment by bearwal** [comment]
I did, still gives me "Cloning into 'F:\Applio'...
Cloning process completed with exit code 0
Finished cloning repository"
 In the tutorials i've watched it usually starts showing more text but thats all It shows after I click install

**Comment by bygimenez** [comment]
Thanks for the warning, it seems to be a problem with Applio Installer. While we fix it I recommend you to install Applio with this .bat https://github.com/IAHispano/Applio-RVC-Fork/releases/download/v2.0.0/install_Applio-windows.bat
